# Generated by Django 5.2.5 on 2025-09-03 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_carrera', models.CharField(max_length=255, unique=True)),
                ('plan_estudios_carrera', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_nivel', models.CharField(max_length=255)),
                ('mcr_nivel', models.CharField(max_length=10)),
                ('horas_nivel', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('matricula_alumno', models.CharField(max_length=20, unique=True)),
                ('nombre_alumno', models.CharField(max_length=100)),
                ('apellidos_alumno', models.CharField(max_length=100)),
                ('edad_alumno', models.PositiveSmallIntegerField()),
                ('sexo_alumno', models.CharField(max_length=50)),
                ('semestre_alumno', models.PositiveSmallIntegerField()),
                ('inscrito', models.BooleanField(default=False)),
                ('acredita', models.BooleanField(default=False)),
                ('liberado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.carrera')),
                ('id_nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.nivel')),
            ],
        ),
    ]
